version: '3.8'
# для зєднання декількох контейнерів tyt
services:
  django_library:
    build: .
    command: sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:4000"

    volumes:
      - ./:/usr/src/
    ports:
      - "8001:4000"
    environment:
      - DEBUG=1
      - SECRET_KEY=1
#      - DB
    depends_on:
      - db  # залежить від postgres
#      - postgres_data # залежить від postgres_data
    restart: always
  db:
    image: postgres:14.5
    volumes:
#      - host_mashina : container
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_library
    ports:
      - "54321:5432"
    restart: always

volumes:
  postgres_data:
