version: '3.8'
# для зєднання декількох контейнерів tyt
services:
  app_library:
    container_name: library_web
    restart: unless-stopped
    build: .
    command: bash -c "python manage.py migrate
      && touch new_file_inside
      && python manage.py runserver 0.0.0.0:5000"

    volumes:
      - ./:/usr/src/
    ports:
      - "7000:5000"  # 5000 we can't see, it's inside container
    env_file:
      - ./.env.dev
    depends_on:
      - db  # залежить від postgres
#      - postgres_data # залежить від postgres_data
  db:
    image: postgres:14.5
    container_name: postgres_db
    volumes:
#      - host_mashina : container port
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_db

    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
