version: '3.8'
# для зєднання декількох контейнерів tyt
services:
  django_library:
    build: .
    command: python manage.py runserver 0.0.0.0:4000
#           && touch new_file_inside
#         python manage.py migrate --noinput &&
    volumes:
      - ./:/usr/src/
    ports:
      - "8001:4000"
    environment:
      - DEBUG=1
      - SECRET_KEY=1
      - DJANGO_ALLOWED_HOSTS=localhost 78.27.202.55 [::1]
#      - DB
    depends_on:
      - db  # залежить від postgres
#      - postgres_data # залежить від postgres_data
  db:
    image: postgres:14.5
    volumes:
#      - host_mashina : container
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_library
    ports:
      - "5432:5432"

volumes:
  postgres_data:
