# Generated by Django 4.1 on 2022-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_remove_author_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Автори'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, verbose_name='по-батькові'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='прізвище'),
        ),
    ]
