# Generated by Django 4.1 on 2022-09-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_book_order_created_at_order_end_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
